name: Deploy to Linux Server

on:
  push:
    branches:
      - main   # Trigger only on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Debug Variables (remove later)
        run: |
          echo "Host is set? -> ${{ secrets.SERVER_HOST != '' }}"
          echo "User is set? -> ${{ secrets.SERVER_USER != '' }}"
          echo "Path is set? -> ${{ secrets.DEPLOY_PATH != '' }}"

      - name: SSH and Pull Latest Code
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e
            echo "Deploying latest code to server..."
            cd ${{ secrets.DEPLOY_PATH }}
            git fetch origin main
            git reset --hard origin/main
            echo "✅ Code pulled successfully!"
