name: Pull Code on Server

on:
  push:
    branches:
      - main   # Trigger when pushing to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo (for build/test if needed)
        uses: actions/checkout@v4

      # Optional: run tests before deploying
      - name: Run tests
        run: |
          echo "Running tests..."
          pytest || echo "Tests failed, skipping deploy"

      - name: SSH and Pull Latest Code
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}   # PRIVATE KEY
          script: |
            set -e
            echo "Pulling latest code on server..."
            cd ${{ secrets.DEPLOY_PATH }}
            git fetch origin main
            git reset --hard origin/main
